/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerapiabrasilRouteImport } from './routes/terapiabrasil'
import { Route as TerapiaAnsiedadeRouteImport } from './routes/terapia-ansiedade'
import { Route as HipnoseEricksonianaRouteImport } from './routes/hipnose-ericksoniana'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as IndexRouteImport } from './routes/index'

const TerapiabrasilRoute = TerapiabrasilRouteImport.update({
  id: '/terapiabrasil',
  path: '/terapiabrasil',
  getParentRoute: () => rootRouteImport,
} as any)
const TerapiaAnsiedadeRoute = TerapiaAnsiedadeRouteImport.update({
  id: '/terapia-ansiedade',
  path: '/terapia-ansiedade',
  getParentRoute: () => rootRouteImport,
} as any)
const HipnoseEricksonianaRoute = HipnoseEricksonianaRouteImport.update({
  id: '/hipnose-ericksoniana',
  path: '/hipnose-ericksoniana',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/hipnose-ericksoniana': typeof HipnoseEricksonianaRoute
  '/terapia-ansiedade': typeof TerapiaAnsiedadeRoute
  '/terapiabrasil': typeof TerapiabrasilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/hipnose-ericksoniana': typeof HipnoseEricksonianaRoute
  '/terapia-ansiedade': typeof TerapiaAnsiedadeRoute
  '/terapiabrasil': typeof TerapiabrasilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/hipnose-ericksoniana': typeof HipnoseEricksonianaRoute
  '/terapia-ansiedade': typeof TerapiaAnsiedadeRoute
  '/terapiabrasil': typeof TerapiabrasilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/hipnose-ericksoniana'
    | '/terapia-ansiedade'
    | '/terapiabrasil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/hipnose-ericksoniana'
    | '/terapia-ansiedade'
    | '/terapiabrasil'
  id:
    | '__root__'
    | '/'
    | '/agendar'
    | '/hipnose-ericksoniana'
    | '/terapia-ansiedade'
    | '/terapiabrasil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendarRoute: typeof AgendarRoute
  HipnoseEricksonianaRoute: typeof HipnoseEricksonianaRoute
  TerapiaAnsiedadeRoute: typeof TerapiaAnsiedadeRoute
  TerapiabrasilRoute: typeof TerapiabrasilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terapiabrasil': {
      id: '/terapiabrasil'
      path: '/terapiabrasil'
      fullPath: '/terapiabrasil'
      preLoaderRoute: typeof TerapiabrasilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terapia-ansiedade': {
      id: '/terapia-ansiedade'
      path: '/terapia-ansiedade'
      fullPath: '/terapia-ansiedade'
      preLoaderRoute: typeof TerapiaAnsiedadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hipnose-ericksoniana': {
      id: '/hipnose-ericksoniana'
      path: '/hipnose-ericksoniana'
      fullPath: '/hipnose-ericksoniana'
      preLoaderRoute: typeof HipnoseEricksonianaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendarRoute: AgendarRoute,
  HipnoseEricksonianaRoute: HipnoseEricksonianaRoute,
  TerapiaAnsiedadeRoute: TerapiaAnsiedadeRoute,
  TerapiabrasilRoute: TerapiabrasilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
